/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_co_cyberagent_android_gpuimage_GPUImageNativeLibrary */

#ifndef _Included_jp_co_cyberagent_android_gpuimage_GPUImageNativeLibrary
#define _Included_jp_co_cyberagent_android_gpuimage_GPUImageNativeLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jp_co_cyberagent_android_gpuimage_GPUImageNativeLibrary
 * Method:    captureGLData
 * Signature: ([I[III)V
 */
JNIEXPORT void JNICALL Java_jp_co_cyberagent_android_gpuimage_GPUImageNativeLibrary_captureGLData
  (JNIEnv *, jclass, jintArray, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
